services:
  auth-service:
    build: ./auth-service
    ports:
      - "4000:3000"
    env_file:
      - ./auth-service/.env
    container_name: auth-service
    command: sh -c "npm run migrate up && npm start"
    depends_on:
      postgres:
        condition: service_healthy

  tip-service:
    build: ./tip-service
    ports:
      - "4001:4001"
    env_file:
      - ./tip-service/.env
    environment:
      AUTH_SERVICE_URL: http://auth-service:3001
    container_name: tip-service
    depends_on:
      tip_postgres:
        condition: service_healthy
    
  billing-service:
    build: ./billing-service
    ports:
      - "4002:4002"
    env_file:
      - ./billing-service/.env
    container_name: billing-service
    command: npm start
    depends_on:
      billing_db:
        condition: service_healthy

  postgres:
    build:
      context: .
      dockerfile: auth-db.Dockerfile
    environment:
      POSTGRES_DB: tips_app_db
      POSTGRES_USER: tips_ulrich_2025
      POSTGRES_PASSWORD: 123qweJesus
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tips_ulrich_2025 -d tips_app_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  tip_postgres:
    build:
      context: .
      dockerfile: tip-db.Dockerfile
    environment:
      POSTGRES_DB: tip_db
      POSTGRES_USER: tip_user
      POSTGRES_PASSWORD: tip_password
    ports:
      - "5434:5432"
    volumes:
      - tip_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tip_user -d tip_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  billing_db:
    build:
      context: .
      dockerfile: billing-db.Dockerfile
    environment:
      POSTGRES_DB: billing_service_db
      POSTGRES_USER: billing_user
      POSTGRES_PASSWORD: billing_password
    ports:
      - "5435:5432"
    volumes:
      - billing_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U billing_user -d billing_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
      tip_postgres:
        condition: service_healthy
      billing_db:
        condition: service_healthy

volumes:
  postgres_data:
  tip_postgres_data:
  billing_postgres_data:
